/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.5 */

#include "monitor.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(monitor_HelloAsync, monitor_HelloAsync, AUTO)


PB_BIND(monitor_Temperature, monitor_Temperature, AUTO)


PB_BIND(monitor_TemperatureAsync, monitor_TemperatureAsync, AUTO)


PB_BIND(monitor_TemperatureGetReq, monitor_TemperatureGetReq, AUTO)


PB_BIND(monitor_TemperatureGetRes, monitor_TemperatureGetRes, AUTO)


PB_BIND(monitor_VersionGetReq, monitor_VersionGetReq, AUTO)


PB_BIND(monitor_VersionGetRes, monitor_VersionGetRes, AUTO)


PB_BIND(monitor_MonitorMsg, monitor_MonitorMsg, AUTO)




