# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: monitor.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import util_pb2 as util__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='monitor.proto',
  package='monitor',
  syntax='proto2',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\rmonitor.proto\x12\x07monitor\x1a\nutil.proto\"\x0c\n\nHelloAsync\"g\n\x0bTemperature\x12-\n\x07\x65lement\x18\x01 \x01(\x0e\x32\x1c.monitor.Temperature.Element\x12\x0c\n\x04temp\x18\x02 \x01(\x02\"\x1b\n\x07\x45lement\x12\x07\n\x03\x43PU\x10\x01\x12\x07\n\x03GPU\x10\x02\">\n\x10TemperatureAsync\x12*\n\x0ctemperatures\x18\x01 \x03(\x0b\x32\x14.monitor.Temperature\"\x13\n\x11TemperatureGetReq\"?\n\x11TemperatureGetRes\x12*\n\x0ctemperatures\x18\x01 \x03(\x0b\x32\x14.monitor.Temperature\"\x0f\n\rVersionGetReq\" \n\rVersionGetRes\x12\x0f\n\x07version\x18\x01 \x01(\x0c\"\x98\x03\n\nMonitorMsg\x12#\n\nmsg_status\x18\x01 \x01(\x0e\x32\x0f.util.MsgStatus\x12\x0b\n\x03uid\x18\x02 \x01(\r\x12\x11\n\ttimestamp\x18\x03 \x01(\x04\x12*\n\x0bhello_async\x18\n \x01(\x0b\x32\x13.monitor.HelloAsyncH\x00\x12\x36\n\x11temperature_async\x18\x0b \x01(\x0b\x32\x19.monitor.TemperatureAsyncH\x00\x12\x39\n\x13temperature_get_req\x18\x0c \x01(\x0b\x32\x1a.monitor.TemperatureGetReqH\x00\x12\x39\n\x13temperature_get_res\x18\r \x01(\x0b\x32\x1a.monitor.TemperatureGetResH\x00\x12\x31\n\x0fversion_get_req\x18\x0e \x01(\x0b\x32\x16.monitor.VersionGetReqH\x00\x12\x31\n\x0fversion_get_res\x18\x0f \x01(\x0b\x32\x16.monitor.VersionGetResH\x00\x42\x05\n\x03msg'
  ,
  dependencies=[util__pb2.DESCRIPTOR,])



_TEMPERATURE_ELEMENT = _descriptor.EnumDescriptor(
  name='Element',
  full_name='monitor.Temperature.Element',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='CPU', index=0, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='GPU', index=1, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=128,
  serialized_end=155,
)
_sym_db.RegisterEnumDescriptor(_TEMPERATURE_ELEMENT)


_HELLOASYNC = _descriptor.Descriptor(
  name='HelloAsync',
  full_name='monitor.HelloAsync',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=38,
  serialized_end=50,
)


_TEMPERATURE = _descriptor.Descriptor(
  name='Temperature',
  full_name='monitor.Temperature',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='element', full_name='monitor.Temperature.element', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='temp', full_name='monitor.Temperature.temp', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _TEMPERATURE_ELEMENT,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=52,
  serialized_end=155,
)


_TEMPERATUREASYNC = _descriptor.Descriptor(
  name='TemperatureAsync',
  full_name='monitor.TemperatureAsync',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='temperatures', full_name='monitor.TemperatureAsync.temperatures', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=157,
  serialized_end=219,
)


_TEMPERATUREGETREQ = _descriptor.Descriptor(
  name='TemperatureGetReq',
  full_name='monitor.TemperatureGetReq',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=221,
  serialized_end=240,
)


_TEMPERATUREGETRES = _descriptor.Descriptor(
  name='TemperatureGetRes',
  full_name='monitor.TemperatureGetRes',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='temperatures', full_name='monitor.TemperatureGetRes.temperatures', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=242,
  serialized_end=305,
)


_VERSIONGETREQ = _descriptor.Descriptor(
  name='VersionGetReq',
  full_name='monitor.VersionGetReq',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=307,
  serialized_end=322,
)


_VERSIONGETRES = _descriptor.Descriptor(
  name='VersionGetRes',
  full_name='monitor.VersionGetRes',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='version', full_name='monitor.VersionGetRes.version', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=324,
  serialized_end=356,
)


_MONITORMSG = _descriptor.Descriptor(
  name='MonitorMsg',
  full_name='monitor.MonitorMsg',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='msg_status', full_name='monitor.MonitorMsg.msg_status', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='uid', full_name='monitor.MonitorMsg.uid', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='monitor.MonitorMsg.timestamp', index=2,
      number=3, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='hello_async', full_name='monitor.MonitorMsg.hello_async', index=3,
      number=10, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='temperature_async', full_name='monitor.MonitorMsg.temperature_async', index=4,
      number=11, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='temperature_get_req', full_name='monitor.MonitorMsg.temperature_get_req', index=5,
      number=12, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='temperature_get_res', full_name='monitor.MonitorMsg.temperature_get_res', index=6,
      number=13, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='version_get_req', full_name='monitor.MonitorMsg.version_get_req', index=7,
      number=14, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='version_get_res', full_name='monitor.MonitorMsg.version_get_res', index=8,
      number=15, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='msg', full_name='monitor.MonitorMsg.msg',
      index=0, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
  ],
  serialized_start=359,
  serialized_end=767,
)

_TEMPERATURE.fields_by_name['element'].enum_type = _TEMPERATURE_ELEMENT
_TEMPERATURE_ELEMENT.containing_type = _TEMPERATURE
_TEMPERATUREASYNC.fields_by_name['temperatures'].message_type = _TEMPERATURE
_TEMPERATUREGETRES.fields_by_name['temperatures'].message_type = _TEMPERATURE
_MONITORMSG.fields_by_name['msg_status'].enum_type = util__pb2._MSGSTATUS
_MONITORMSG.fields_by_name['hello_async'].message_type = _HELLOASYNC
_MONITORMSG.fields_by_name['temperature_async'].message_type = _TEMPERATUREASYNC
_MONITORMSG.fields_by_name['temperature_get_req'].message_type = _TEMPERATUREGETREQ
_MONITORMSG.fields_by_name['temperature_get_res'].message_type = _TEMPERATUREGETRES
_MONITORMSG.fields_by_name['version_get_req'].message_type = _VERSIONGETREQ
_MONITORMSG.fields_by_name['version_get_res'].message_type = _VERSIONGETRES
_MONITORMSG.oneofs_by_name['msg'].fields.append(
  _MONITORMSG.fields_by_name['hello_async'])
_MONITORMSG.fields_by_name['hello_async'].containing_oneof = _MONITORMSG.oneofs_by_name['msg']
_MONITORMSG.oneofs_by_name['msg'].fields.append(
  _MONITORMSG.fields_by_name['temperature_async'])
_MONITORMSG.fields_by_name['temperature_async'].containing_oneof = _MONITORMSG.oneofs_by_name['msg']
_MONITORMSG.oneofs_by_name['msg'].fields.append(
  _MONITORMSG.fields_by_name['temperature_get_req'])
_MONITORMSG.fields_by_name['temperature_get_req'].containing_oneof = _MONITORMSG.oneofs_by_name['msg']
_MONITORMSG.oneofs_by_name['msg'].fields.append(
  _MONITORMSG.fields_by_name['temperature_get_res'])
_MONITORMSG.fields_by_name['temperature_get_res'].containing_oneof = _MONITORMSG.oneofs_by_name['msg']
_MONITORMSG.oneofs_by_name['msg'].fields.append(
  _MONITORMSG.fields_by_name['version_get_req'])
_MONITORMSG.fields_by_name['version_get_req'].containing_oneof = _MONITORMSG.oneofs_by_name['msg']
_MONITORMSG.oneofs_by_name['msg'].fields.append(
  _MONITORMSG.fields_by_name['version_get_res'])
_MONITORMSG.fields_by_name['version_get_res'].containing_oneof = _MONITORMSG.oneofs_by_name['msg']
DESCRIPTOR.message_types_by_name['HelloAsync'] = _HELLOASYNC
DESCRIPTOR.message_types_by_name['Temperature'] = _TEMPERATURE
DESCRIPTOR.message_types_by_name['TemperatureAsync'] = _TEMPERATUREASYNC
DESCRIPTOR.message_types_by_name['TemperatureGetReq'] = _TEMPERATUREGETREQ
DESCRIPTOR.message_types_by_name['TemperatureGetRes'] = _TEMPERATUREGETRES
DESCRIPTOR.message_types_by_name['VersionGetReq'] = _VERSIONGETREQ
DESCRIPTOR.message_types_by_name['VersionGetRes'] = _VERSIONGETRES
DESCRIPTOR.message_types_by_name['MonitorMsg'] = _MONITORMSG
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

HelloAsync = _reflection.GeneratedProtocolMessageType('HelloAsync', (_message.Message,), {
  'DESCRIPTOR' : _HELLOASYNC,
  '__module__' : 'monitor_pb2'
  # @@protoc_insertion_point(class_scope:monitor.HelloAsync)
  })
_sym_db.RegisterMessage(HelloAsync)

Temperature = _reflection.GeneratedProtocolMessageType('Temperature', (_message.Message,), {
  'DESCRIPTOR' : _TEMPERATURE,
  '__module__' : 'monitor_pb2'
  # @@protoc_insertion_point(class_scope:monitor.Temperature)
  })
_sym_db.RegisterMessage(Temperature)

TemperatureAsync = _reflection.GeneratedProtocolMessageType('TemperatureAsync', (_message.Message,), {
  'DESCRIPTOR' : _TEMPERATUREASYNC,
  '__module__' : 'monitor_pb2'
  # @@protoc_insertion_point(class_scope:monitor.TemperatureAsync)
  })
_sym_db.RegisterMessage(TemperatureAsync)

TemperatureGetReq = _reflection.GeneratedProtocolMessageType('TemperatureGetReq', (_message.Message,), {
  'DESCRIPTOR' : _TEMPERATUREGETREQ,
  '__module__' : 'monitor_pb2'
  # @@protoc_insertion_point(class_scope:monitor.TemperatureGetReq)
  })
_sym_db.RegisterMessage(TemperatureGetReq)

TemperatureGetRes = _reflection.GeneratedProtocolMessageType('TemperatureGetRes', (_message.Message,), {
  'DESCRIPTOR' : _TEMPERATUREGETRES,
  '__module__' : 'monitor_pb2'
  # @@protoc_insertion_point(class_scope:monitor.TemperatureGetRes)
  })
_sym_db.RegisterMessage(TemperatureGetRes)

VersionGetReq = _reflection.GeneratedProtocolMessageType('VersionGetReq', (_message.Message,), {
  'DESCRIPTOR' : _VERSIONGETREQ,
  '__module__' : 'monitor_pb2'
  # @@protoc_insertion_point(class_scope:monitor.VersionGetReq)
  })
_sym_db.RegisterMessage(VersionGetReq)

VersionGetRes = _reflection.GeneratedProtocolMessageType('VersionGetRes', (_message.Message,), {
  'DESCRIPTOR' : _VERSIONGETRES,
  '__module__' : 'monitor_pb2'
  # @@protoc_insertion_point(class_scope:monitor.VersionGetRes)
  })
_sym_db.RegisterMessage(VersionGetRes)

MonitorMsg = _reflection.GeneratedProtocolMessageType('MonitorMsg', (_message.Message,), {
  'DESCRIPTOR' : _MONITORMSG,
  '__module__' : 'monitor_pb2'
  # @@protoc_insertion_point(class_scope:monitor.MonitorMsg)
  })
_sym_db.RegisterMessage(MonitorMsg)


# @@protoc_insertion_point(module_scope)
